### ISSUE TITLE
Waypoint (for Capture Point)

### ISSUE THREAD

**Issue by trayer3** [trayer3/DeathCube#30]
Waypoint:
- Decide who gets to see the waypoints.  All teams see all points?  Or only team sees team's point?
- Change color to match Team.  [Done]
- Upgrade graphic from placeholder (future)

**Comment by trayer3** [comment]
Make solid / non-transparent to avoid conflicting rendering with other transparent blocks.
Remove shadow from under waypoint.  Possible?

**Comment by TechStack** [comment]
They are not transparent... things like water /glass that are transparent are rendered after other objects in the game making the Waypoints render behind them even though they have their depth bit disabled in open GL :(

one of the ways others have bypassed this is to have it technically render right int he players face and scale it to look off int he distance... seems like a pain to achieve the results.
need to investigate more later
